name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    
    - name: Vérifier PHP et Composer
      run: |
        php -v
        composer --version

    - name: Installer PHP avec extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, exif, pcntl, bcmath

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Dependencies (Debug)
      run: composer install --prefer-dist --no-progress --no-interaction --verbose

    - name: Installer les dépendances
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Générer la clé d’application
      run: php src/artisan key:generate

